Update batcher.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/kaggle/working/model-pretrain/Text-Summarizer-Pytorch/data_util/batcher.py", line 273, in text_generator
    e = next(example_generator) # e is a tf.Example
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/kaggle/working/model-pretrain/Text-Summarizer-Pytorch/data_util/batcher.py", line 210, in fill_example_queue
    (article, abstract) = next(input_gen) # read the next example from file. article and abstract are both strings.
RuntimeError: generator raised StopIteration

解决这个